### ISSUE TITLE
How to change the Buffer size in Tcp StreamChannel?

### ISSUE THREAD

**Issue by mayamoon** [StormHub/NetworkCore#1]
Very impress project,i am looking for a Libuv wapper for .netcore long time ago.
Thank you !
Do you  plan to add more detail document?
please add more example, like chart room ... 
i found when Tcp IStreamChannel  WriteAsync  message length great than 1024 will caurse exception ,but i don't known how to fix it ,please help!.

**Comment by StormHub** [comment]
@mayamoon just double check, is this still an issue? I think I have already fixed this properly based on some feedback.
