### ISSUE TITLE
how can i use multi event loop?

### ISSUE THREAD

**Issue by egmkang** [StormHub/NetworkCore#70]
how can i use multi threads to improve the throughput?

**Comment by StormHub** [comment]
You can use one loop to dispatch incoming connections into multiple loops. I will add an example shortly.

**Comment by egmkang** [comment]
thank you very much

**Comment by StormHub** [comment]
Please have a look at the files under https://github.com/StormHub/NetUV/tree/dev/examples/LoopThread

**Comment by egmkang** [comment]
@StormHub 
thankds very much

http://docs.libuv.org/en/v1.x/guide/processes.html#sending-file-descriptors-over-pipes

the c# version is similar with the c version.
